apiVersion: v1
kind: Secret
metadata:
  name: {{ template "my-db.fullname" . }}-secret
type: Opaque
data:
  pg-db-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  pg-db-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}