apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
 # name: {{ include "my-db.fullname" . }}
  labels:
    {{- include "my-db.labels" . | nindent 4 }}   
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
   {{- include "my-db.selectorLabels" . | nindent 4 }}
